apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: flask-mongodb-ns
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: flask-mongodb-ns
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None