apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-mongodb-ns
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
  type: NodePort